## Advent of Code 2024 - Day 12

In [1]:
from rich import print
from httpx import request
import os
import numpy as np
from itertools import product
import math
import functools

%load_ext rich

In [41]:
def parse_input(path):
    # Read file and split into lines
    with open(path, "r") as file:
        result = file.read().splitlines()
    # Optional: Remove any empty lines if needed
    return [line for line in result]

In [42]:
sample_input = parse_input("sample.txt")
sample_input_2 = parse_input("sample_2.txt")
sample_input_3 = parse_input("sample_3.txt")
actual_input = parse_input("input.txt")

## Part 1

In [43]:
sample_input


['AAAA', 'BBCD', 'BBCC', 'EEEC']

In [107]:
floor_map


array([['R', 'R', 'R', 'R', 'I', 'I', 'C', 'C', 'F', 'F'],
       ['R', 'R', 'R', 'R', 'I', 'I', 'C', 'C', 'C', 'F'],
       ['V', 'V', 'R', 'R', 'R', 'C', 'C', 'F', 'F', 'F'],
       ['V', 'V', 'R', 'C', 'C', 'C', 'J', 'F', 'F', 'F'],
       ['V', 'V', 'V', 'V', 'C', 'J', 'J', 'C', 'F', 'E'],
       ['V', 'V', 'I', 'V', 'C', 'C', 'J', 'J', 'E', 'E'],
       ['V', 'V', 'I', 'I', 'I', 'C', 'J', 'J', 'E', 'E'],
       ['M', 'I', 'I', 'I', 'I', 'I', 'J', 'J', 'E', 'E'],
       ['M', 'I', 'I', 'I', 'S', 'I', 'J', 'E', 'E', 'E'],
       ['M', 'M', 'M', 'I', 'S', 'S', 'J', 'E', 'E', 'E']], dtype='<U1')

In [100]:
floor_map = np.array([list(line) for line in sample_input_3])
floor_map
m, n = floor_map.shape

types_of_plants = {x: [np.where(floor_map == x)] for x in np.unique(floor_map)}
types_of_plants


{
    np.str_('C'): [
        (
            array([0, 0, 1, 1, 1, 2, 2, 3, 3, 3, 4, 4, 5, 5, 6]),
            array([6, 7, 6, 7, 8, 5, 6, 3, 4, 5, 4, 7, 4, 5, 5])
        )
    ],
    np.str_('E'): [
        (
            array([4, 5, 5, 6, 6, 7, 7, 8, 8, 8, 9, 9, 9]),
            array([9, 8, 9, 8, 9, 8, 9, 7, 8, 9, 7, 8, 9])
        )
    ],
    np.str_('F'): [(array([0, 0, 1, 2, 2, 2, 3, 3, 3, 4]), array([8, 9, 9, 7, 8, 9, 7, 8, 9, 8]))],
    np.str_('I'): [
        (
            array([0, 0, 1, 1, 5, 6, 6, 6, 7, 7, 7, 7, 7, 8, 8, 8, 8, 9]),
            array([4, 5, 4, 5, 2, 2, 3, 4, 1, 2, 3, 4, 5, 1, 2, 3, 5, 3])
        )
    ],
    np.str_('J'): [
        (array([3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 9]), array([6, 5, 6, 6, 7, 6, 7, 6, 7, 6, 6]))
    ],
    np.str_('M'): [(array([7, 8, 9, 9, 9]), array([0, 0, 0, 1, 2]))],
    np.str_('R'): [
        (array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 3]), array([0, 1, 2, 3, 0, 1, 2, 3, 2, 3, 4, 2]))
    ],
    np.str_('S'): [(array([8, 9, 9]), arr

In [170]:
def draw_region(floor_map, plant):
    fm_copy = floor_map.copy()
    fm_copy[fm_copy == plant] = plant
    fm_copy[fm_copy != plant] = "."

    return fm_copy


def crawl_regions(floor_map, plant):
    fm_copy = floor_map.copy()
    plant_positions = types_of_plants[plant]

    x_coords, y_coords = plant_positions[0]

    region_sets = []
    region_set = set()

    for i in range(len(x_coords)):
        print(f"Plant {plant} position: ({x_coords[i]}, {y_coords[i]})")

        direction_check = {
            "S": (1, 0),
            "N": (-1, 0),
            "E": (0, -1),
            "W": (0, 1),
        }

        direction_plants = {}

        for direction, (di, dj) in direction_check.items():
            new_x, new_y = x_coords[i] + di, y_coords[i] + dj

            if 0 <= new_x < m and 0 <= new_y < n:
                direction_plants[direction] = floor_map[
                    x_coords[i] + di, y_coords[i] + dj
                ]

            else:
                direction_plants[direction] = "-1"

    print(f"Plant: {plant}")
    print(draw_region(floor_map, plant))
    print()
    print("Plant positions: {}".format(plant_positions))

In [180]:
import fileinput
g = {
    (x, y): c
    for y, r in enumerate(fileinput.input("sample_3.txt"))
    for x, c in enumerate(r.strip("\n"))
}

g


{
    (0, 0): 'R',
    (1, 0): 'R',
    (2, 0): 'R',
    (3, 0): 'R',
    (4, 0): 'I',
    (5, 0): 'I',
    (6, 0): 'C',
    (7, 0): 'C',
    (8, 0): 'F',
    (9, 0): 'F',
    (0, 1): 'R',
    (1, 1): 'R',
    (2, 1): 'R',
    (3, 1): 'R',
    (4, 1): 'I',
    (5, 1): 'I',
    (6, 1): 'C',
    (7, 1): 'C',
    (8, 1): 'C',
    (9, 1): 'F',
    (0, 2): 'V',
    (1, 2): 'V',
    (2, 2): 'R',
    (3, 2): 'R',
    (4, 2): 'R',
    (5, 2): 'C',
    (6, 2): 'C',
    (7, 2): 'F',
    (8, 2): 'F',
    (9, 2): 'F',
    (0, 3): 'V',
    (1, 3): 'V',
    (2, 3): 'R',
    (3, 3): 'C',
    (4, 3): 'C',
    (5, 3): 'C',
    (6, 3): 'J',
    (7, 3): 'F',
    (8, 3): 'F',
    (9, 3): 'F',
    (0, 4): 'V',
    (1, 4): 'V',
    (2, 4): 'V',
    (3, 4): 'V',
    (4, 4): 'C',
    (5, 4): 'J',
    (6, 4): 'J',
    (7, 4): 'C',
    (8, 4): 'F',
    (9, 4): 'E',
    (0, 5): 'V',
    (1, 5): 'V',
    (2, 5): 'I',
    (3, 5): 'V',
    (4, 5): 'C',
    (5, 5): 'C',
    (6, 5): 'J',
    (7, 5): 'J',
    (8, 5):

In [191]:
import scipy

d = scipy.cluster.hierarchy.DisjointSet(g)

for (x, y), v in g.items():
    for n in ((x - 1, y), (x + 1, y), (x, y - 1), (x, y + 1)):
        if g.get(n, None) == v:
            d.merge((x, y), n)

d.subsets()


[
    {(0, 1), (2, 1), (0, 0), (3, 1), (1, 1), (2, 0), (4, 2), (3, 0), (2, 3), (2, 2), (1, 0), (3, 2)},
    {(5, 0), (4, 0), (4, 1), (5, 1)},
    {
        (4, 4),
        (6, 2),
        (5, 5),
        (7, 1),
        (4, 3),
        (8, 1),
        (6, 1),
        (7, 0),
        (4, 5),
        (3, 3),
        (5, 6),
        (6, 0),
        (5, 3),
        (5, 2)
    },
    {(9, 0), (8, 4), (9, 3), (9, 2), (8, 0), (7, 3), (8, 3), (7, 2), (8, 2), (9, 1)},
    {
        (2, 4),
        (1, 2),
        (0, 4),
        (3, 4),
        (1, 5),
        (0, 3),
        (1, 4),
        (0, 6),
        (0, 2),
        (0, 5),
        (1, 6),
        (1, 3),
        (3, 5)
    },
    {(7, 7), (6, 5), (6, 8), (5, 4), (6, 4), (6, 7), (7, 6), (6, 6), (7, 5), (6, 3), (6, 9)},
    {(7, 4)},
    {
        (8, 8),
        (9, 9),
        (8, 7),
        (9, 6),
        (7, 9),
        (9, 5),
        (8, 9),
        (9, 8),
        (8, 6),
        (9, 7),
        (8, 5),
        (7, 8),
        (

In [171]:
crawl_regions(floor_map, "I")

Plant I position: (0, 4)

{(np.int64(1), np.int64(4)), (np.int64(0), np.int64(5))}

Plant I position: (0, 5)

{(np.int64(1), np.int64(5)), (np.int64(0), np.int64(4)), (np.int64(1), np.int64(4)), (np.int64(0), np.int64(5))}

Plant I position: (1, 4)

{(np.int64(1), np.int64(5)), (np.int64(0), np.int64(4)), (np.int64(1), np.int64(4)), (np.int64(0), np.int64(5))}

Plant I position: (1, 5)

{(np.int64(1), np.int64(5)), (np.int64(0), np.int64(4)), (np.int64(1), np.int64(4)), (np.int64(0), np.int64(5))}

Plant I position: (5, 2)

{
    (np.int64(6), np.int64(2)),
    (np.int64(0), np.int64(4)),
    (np.int64(1), np.int64(5)),
    (np.int64(1), np.int64(4)),
    (np.int64(0), np.int64(5))
}

Plant I position: (6, 2)

{
    (np.int64(6), np.int64(2)),
    (np.int64(0), np.int64(4)),
    (np.int64(1), np.int64(5)),
    (np.int64(1), np.int64(4)),
    (np.int64(0), np.int64(5)),
    (np.int64(7), np.int64(2)),
    (np.int64(6), np.int64(3)),
    (np.int64(5), np.int64(2))
}

Plant I position: (6, 3)

{
    (np.int64(6), np.int64(2)),
    (np.int64(0), np.int64(4)),
    (np.int64(1), np.int64(5)),
    (np.int64(6), np.int64(4)),
    (np.int64(1), np.int64(4)),
    (np.int64(7), np.int64(3)),
    (np.int64(0), np.int64(5)),
    (np.int64(7), np.int64(2)),
    (np.int64(6), np.int64(3)),
    (np.int64(5), np.int64(2))
}

Plant I position: (6, 4)

{
    (np.int64(7), np.int64(4)),
    (np.int64(6), np.int64(2)),
    (np.int64(0), np.int64(4)),
    (np.int64(1), np.int64(5)),
    (np.int64(6), np.int64(4)),
    (np.int64(1), np.int64(4)),
    (np.int64(7), np.int64(3)),
    (np.int64(0), np.int64(5)),
    (np.int64(7), np.int64(2)),
    (np.int64(6), np.int64(3)),
    (np.int64(5), np.int64(2))
}

Plant I position: (7, 1)

{
    (np.int64(7), np.int64(4)),
    (np.int64(6), np.int64(2)),
    (np.int64(0), np.int64(4)),
    (np.int64(1), np.int64(5)),
    (np.int64(8), np.int64(1)),
    (np.int64(6), np.int64(4)),
    (np.int64(1), np.int64(4)),
    (np.int64(7), np.int64(3)),
    (np.int64(0), np.int64(5)),
    (np.int64(7), np.int64(2)),
    (np.int64(6), np.int64(3)),
    (np.int64(5), np.int64(2))
}

Plant I position: (7, 2)

{
    (np.int64(7), np.int64(4)),
    (np.int64(6), np.int64(2)),
    (np.int64(0), np.int64(4)),
    (np.int64(7), np.int64(1)),
    (np.int64(1), np.int64(5)),
    (np.int64(8), np.int64(1)),
    (np.int64(6), np.int64(4)),
    (np.int64(1), np.int64(4)),
    (np.int64(7), np.int64(3)),
    (np.int64(0), np.int64(5)),
    (np.int64(7), np.int64(2)),
    (np.int64(8), np.int64(2)),
    (np.int64(6), np.int64(3)),
    (np.int64(5), np.int64(2))
}

Plant I position: (7, 3)

{
    (np.int64(7), np.int64(4)),
    (np.int64(6), np.int64(2)),
    (np.int64(0), np.int64(4)),
    (np.int64(7), np.int64(1)),
    (np.int64(1), np.int64(5)),
    (np.int64(8), np.int64(1)),
    (np.int64(6), np.int64(4)),
    (np.int64(1), np.int64(4)),
    (np.int64(7), np.int64(3)),
    (np.int64(8), np.int64(3)),
    (np.int64(0), np.int64(5)),
    (np.int64(7), np.int64(2)),
    (np.int64(8), np.int64(2)),
    (np.int64(6), np.int64(3)),
    (np.int64(5), np.int64(2))
}

Plant I position: (7, 4)

{
    (np.int64(7), np.int64(4)),
    (np.int64(6), np.int64(2)),
    (np.int64(0), np.int64(4)),
    (np.int64(7), np.int64(1)),
    (np.int64(1), np.int64(5)),
    (np.int64(8), np.int64(1)),
    (np.int64(6), np.int64(4)),
    (np.int64(1), np.int64(4)),
    (np.int64(7), np.int64(3)),
    (np.int64(8), np.int64(3)),
    (np.int64(0), np.int64(5)),
    (np.int64(7), np.int64(2)),
    (np.int64(8), np.int64(2)),
    (np.int64(7), np.int64(5)),
    (np.int64(6), np.int64(3)),
    (np.int64(5), np.int64(2))
}

Plant I position: (7, 5)

{
    (np.int64(7), np.int64(4)),
    (np.int64(6), np.int64(2)),
    (np.int64(0), np.int64(4)),
    (np.int64(7), np.int64(1)),
    (np.int64(1), np.int64(5)),
    (np.int64(8), np.int64(1)),
    (np.int64(6), np.int64(4)),
    (np.int64(1), np.int64(4)),
    (np.int64(7), np.int64(3)),
    (np.int64(8), np.int64(3)),
    (np.int64(0), np.int64(5)),
    (np.int64(7), np.int64(2)),
    (np.int64(8), np.int64(2)),
    (np.int64(7), np.int64(5)),
    (np.int64(6), np.int64(3)),
    (np.int64(8), np.int64(5)),
    (np.int64(5), np.int64(2))
}

Plant I position: (8, 1)

{
    (np.int64(7), np.int64(4)),
    (np.int64(6), np.int64(2)),
    (np.int64(0), np.int64(4)),
    (np.int64(7), np.int64(1)),
    (np.int64(1), np.int64(5)),
    (np.int64(8), np.int64(1)),
    (np.int64(6), np.int64(4)),
    (np.int64(1), np.int64(4)),
    (np.int64(7), np.int64(3)),
    (np.int64(8), np.int64(3)),
    (np.int64(0), np.int64(5)),
    (np.int64(7), np.int64(2)),
    (np.int64(8), np.int64(2)),
    (np.int64(7), np.int64(5)),
    (np.int64(6), np.int64(3)),
    (np.int64(8), np.int64(5)),
    (np.int64(5), np.int64(2))
}

Plant I position: (8, 2)

{
    (np.int64(7), np.int64(4)),
    (np.int64(6), np.int64(2)),
    (np.int64(0), np.int64(4)),
    (np.int64(7), np.int64(1)),
    (np.int64(1), np.int64(5)),
    (np.int64(8), np.int64(1)),
    (np.int64(6), np.int64(4)),
    (np.int64(1), np.int64(4)),
    (np.int64(7), np.int64(3)),
    (np.int64(8), np.int64(3)),
    (np.int64(0), np.int64(5)),
    (np.int64(7), np.int64(2)),
    (np.int64(8), np.int64(2)),
    (np.int64(7), np.int64(5)),
    (np.int64(6), np.int64(3)),
    (np.int64(8), np.int64(5)),
    (np.int64(5), np.int64(2))
}

Plant I position: (8, 3)

{
    (np.int64(7), np.int64(4)),
    (np.int64(6), np.int64(2)),
    (np.int64(0), np.int64(4)),
    (np.int64(7), np.int64(1)),
    (np.int64(9), np.int64(3)),
    (np.int64(1), np.int64(5)),
    (np.int64(8), np.int64(1)),
    (np.int64(6), np.int64(4)),
    (np.int64(1), np.int64(4)),
    (np.int64(7), np.int64(3)),
    (np.int64(8), np.int64(3)),
    (np.int64(0), np.int64(5)),
    (np.int64(7), np.int64(2)),
    (np.int64(8), np.int64(2)),
    (np.int64(7), np.int64(5)),
    (np.int64(6), np.int64(3)),
    (np.int64(8), np.int64(5)),
    (np.int64(5), np.int64(2))
}

Plant I position: (8, 5)

{
    (np.int64(7), np.int64(4)),
    (np.int64(6), np.int64(2)),
    (np.int64(0), np.int64(4)),
    (np.int64(7), np.int64(1)),
    (np.int64(9), np.int64(3)),
    (np.int64(1), np.int64(5)),
    (np.int64(8), np.int64(1)),
    (np.int64(6), np.int64(4)),
    (np.int64(1), np.int64(4)),
    (np.int64(7), np.int64(3)),
    (np.int64(8), np.int64(3)),
    (np.int64(0), np.int64(5)),
    (np.int64(7), np.int64(2)),
    (np.int64(8), np.int64(2)),
    (np.int64(7), np.int64(5)),
    (np.int64(6), np.int64(3)),
    (np.int64(8), np.int64(5)),
    (np.int64(5), np.int64(2))
}

Plant I position: (9, 3)

{
    (np.int64(7), np.int64(4)),
    (np.int64(6), np.int64(2)),
    (np.int64(0), np.int64(4)),
    (np.int64(7), np.int64(1)),
    (np.int64(9), np.int64(3)),
    (np.int64(1), np.int64(5)),
    (np.int64(8), np.int64(1)),
    (np.int64(6), np.int64(4)),
    (np.int64(1), np.int64(4)),
    (np.int64(7), np.int64(3)),
    (np.int64(8), np.int64(3)),
    (np.int64(0), np.int64(5)),
    (np.int64(7), np.int64(2)),
    (np.int64(8), np.int64(2)),
    (np.int64(7), np.int64(5)),
    (np.int64(6), np.int64(3)),
    (np.int64(8), np.int64(5)),
    (np.int64(5), np.int64(2))
}

Plant: I

[['.' '.' '.' '.' 'I' 'I' '.' '.' '.' '.']
 ['.' '.' '.' '.' 'I' 'I' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' 'I' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' 'I' 'I' 'I' '.' '.' '.' '.' '.']
 ['.' 'I' 'I' 'I' 'I' 'I' '.' '.' '.' '.']
 ['.' 'I' 'I' 'I' '.' 'I' '.' '.' '.' '.']
 ['.' '.' '.' 'I' '.' '.' '.' '.' '.' '.']]

Plant positions: [(array([0, 0, 1, 1, 5, 6, 6, 6, 7, 7, 7, 7, 7, 8, 8, 8, 8, 9]), array([4, 5, 4, 5, 2, 2, 3, 4, 1,
2, 3, 4, 5, 1, 2, 3, 5, 3]))]

In [54]:
sample_input_2

['OOOOO', 'OXOXO', 'OOOOO', 'OXOXO', 'OOOOO']

In [7]:
sample_input_3


[
    ['RRRRIICCFF'],
    ['RRRRIICCCF'],
    ['VVRRRCCFFF'],
    ['VVRCCCJFFF'],
    ['VVVVCJJCFE'],
    ['VVIVCCJJEE'],
    ['VVIIICJJEE'],
    ['MIIIIIJJEE'],
    ['MIIISIJEEE'],
    ['MMMISSJEEE']
]

In [6]:
@functools.cache
def process_stone(stone, t):
    """
    Recursive function that takes in a stone and processing step (t). `t` here is the number of blinks to be performed.

    When t == 0, the stone has no more blinks and we return 1
    If the stone is 0, then the next blink in the sequence will be with value 1
    If the number of digits in the number is odd, then the next blink in the sequence will be with value * 2024
    Otherwise, we split the number in the middle into left and right digits, and start their blink sequence from the next blink

    This will then return the number of stones generated for a given input after `t` number of blinks.

    Example:
    stone = 2024, t = 2
    -> stone = 20, t = 1;;stone = 24, t = 1
    -> stone = 2, t = 1; stone = 0, t = 1;;stone = 2, t = 1; stone = 4, t = 1
    -> stone = 4048, t = 0; stone = 1, t = 0;;stone = 4048, t = 0; stone = 8096, t = 0
    -> 1 + 1;;1 + 1
    -> 2 + 2
    -> 2
    """
    if t == 0:
        return 1
    if stone == 0:
        return process_stone(1, t - 1)

    num_digits = int(math.log10(stone)) + 1

    if num_digits % 2:
        return process_stone(stone * 2024, t - 1)

    q, r = divmod(stone, (10 ** (num_digits // 2)))
    return process_stone(q, t - 1) + process_stone(r, t - 1)

In [7]:
def solution_1(input, num_blinks=25):
    stone_line = input.copy()

    total_stones = sum(map(functools.partial(process_stone, t=num_blinks), stone_line))

    return total_stones

In [8]:
print(f"Part 1 - Sample: {solution_1(sample_input_2)}")
print(f"Part 1 - Actual: {solution_1(actual_input)}")


Part 1 - Sample: 55312

Part 1 - Actual: 213625

## Part 2

In [9]:
def solution_2(input, num_blinks=75):
    stone_line = input.copy()

    total_stones = sum(map(functools.partial(process_stone, t=num_blinks), stone_line))

    return total_stones

In [10]:
print(f"Part 2 - Sample: {solution_2(sample_input_2)}")
print(f"Part 2 - Actual: {solution_2(actual_input)}")


Part 2 - Sample: 65601038650482

Part 2 - Actual: 252442982856820